### PR TITLE
Fix two critical bugs in PWI

### PR DESCRIPTION
**Pull request by wd40bomber7**
Just a couple bugs I hit on that seemed relatively critical.

Player data isn't saved on server shutdown, and deserializing items was broken. 

Thanks!

### CODE REVIEW

**Comment by Gnat008** [comment]
1) Technically player data is saved on server shutdown as it is saved when a player leaves the server. Given that a shutdown typically kicks all players, their data would then be saved.

2) The item serialization is valid, however you got the fix wrong. The logic check should be `if (format >= 1)`.

Also, tabs vs spaces. ;)

**Comment by Gnat008** [comment]
Just tested, I am correct. Data is saved already when the server shuts down.

**Comment by wd40bomber7** [comment]
Both bugs continue to repro on our server without these fixes.
PerWorldInventory is unloaded before players are disconnected.

Here is a snippet of the logs:
`[23:08:20] [Server thread/INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[23:08:20] [Server thread/INFO]: [PlotSquared] Disabling PlotSquared v3.3.3
[23:08:20] [Server thread/INFO]: [PerWorldInventory] Disabling PerWorldInventory v1.8.0
[23:08:20] [Server thread/INFO]: [SignURLs] Disabling SignURLs v1.0.5
[23:08:20] [Server thread/INFO]: [Dynmap-Essentials] Disabling Dynmap-Essentials v0.80
[23:08:20] [Server thread/INFO]: [EnjinMinecraftPlugin] Disabling EnjinMinecraftPlugin v2.7.7
[23:08:20] [Server thread/INFO]: [MassiveCore] Disabling MassiveCore v2.8.7Beta
[23:08:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1m[0;31;1mDeactivated Integration [0;35;1mIntegrationVault[m
[23:08:20] [Server thread/INFO]: [0;36;22m[[0;36;1mMassiveCore 2.8.7Beta[0;36;22m] [0;33;1mDisabled[m
[23:08:20] [Server thread/INFO]: [SalvageSmelter] Disabling SalvageSmelter v0.1.8
[23:08:20] [Server thread/INFO]: [ChairStairs] Disabling ChairStairs v1.1
[23:08:20] [Server thread/INFO]: [ChairStairs] has been disabled.
[23:08:20] [Server thread/INFO]: [Vault] Disabling Vault v1.5.6-b49
[23:08:20] [Server thread/INFO]: [OreGenerator-Wd] Disabling OreGenerator-Wd v0.0.0.1
[23:08:20] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4
[23:08:20] [Server thread/INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[23:08:20] [Server thread/INFO]: [EssentialsChat] Disabling EssentialsChat vTeamCity
[23:08:20] [Server thread/INFO]: Essentials: Using config file enhanced permissions.
[23:08:20] [Server thread/INFO]: Permissions listed in as player-commands will be given to all users.
[23:08:20] [Server thread/INFO]: [DailyLoginRewards] Disabling DailyLoginRewards v0.2.1
[23:08:20] [Server thread/INFO]: [DailyLoginRewards] DailyLoginRewards by [BadReuben] V.0.2.1 disabled!
[23:08:20] [Server thread/INFO]: [BlazeFly] Disabling BlazeFly v2.2.1
[23:08:20] [Server thread/INFO]: [HostHordeHealth] Disabling HostHordeHealth v2
[23:08:20] [Server thread/INFO]: [dynmap-mobs] Disabling dynmap-mobs v1.1.1
[23:08:20] [Server thread/INFO]: [AutoSaveWorld] Disabling AutoSaveWorld v4.15.dev
[23:08:21] [Async Chat Thread - #2/INFO]: <[0;31;22mwd40bomber7[m> Restarting[m
[23:08:26] [Server thread/INFO]: [Scribe] Disabling Scribe v0.2.4
[23:08:26] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.0.1
[23:08:26] [Server thread/INFO]: [Votifier] Disabling Votifier v1.9
[23:08:26] [Server thread/INFO]: [Votifier] Votifier disabled.
[23:08:26] [Server thread/INFO]: [WorldBorder] Disabling WorldBorder v1.8.5
[23:08:26] [Server thread/INFO]: [WorldBorder] [CONFIG] Border-checking timed task stopped.
[23:08:26] [Server thread/INFO]: [Advanced_Item_Effects_2] Disabling Advanced_Item_Effects_2 v0.0.2
[23:08:26] [Server thread/INFO]: [XPSigns] Disabling XPSigns v1.2
[23:08:26] [Server thread/INFO]: [XPSigns] XPSings 1.2 by Eyrian unloaded successfully.
[23:08:26] [Server thread/INFO]: [Essentials] Disabling Essentials vTeamCity
[23:08:26] [Server thread/INFO]: [SpawnerTransformPermission] Disabling SpawnerTransformPermission v0.0.2
[23:08:26] [Server thread/INFO]: [EggCatcher] Disabling EggCatcher v2.5
[23:08:26] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v6.1.2;b3fbe8b
[23:08:26] [Server thread/INFO]: [VoteRoulette] Disabling VoteRoulette v3.1.1
[23:08:26] [Server thread/INFO]: [VoteRoulette] Disabled!
[23:08:26] [Server thread/INFO]: [dynmap] Disabling dynmap v2.3-SNAPSHOT-1137
[23:08:26] [Server thread/INFO]: [dynmap] Unloaded 11 components.
[23:08:26] [Server thread/INFO]: [dynmap] Stopping map renderer...
[23:08:27] [Server thread/INFO]: [dynmap] Saved 127 pending tile renders in world 'Survival'
[23:08:27] [Server thread/INFO]: [dynmap] Saved 4 pending tile renders in world 'Plotworld'
[23:08:32] [Server thread/INFO]: [dynmap] Disabled
[23:08:32] [Server thread/INFO]: [Autocrafter] Disabling Autocrafter v0.1.3
[23:08:32] [Server thread/INFO]: [CoreProtect] Disabling CoreProtect v2.12.0
[23:08:32] [Server thread/INFO]: [MaxBans] Disabling MaxBans v2.0
[23:08:32] [Server thread/INFO]: [MaxBans] Disabling Maxbans...
[23:08:32] [Server thread/INFO]: [MaxBans] Clearing buffer...
[23:08:32] [Server thread/INFO]: [MaxBans] Cleared buffer...
[23:08:32] [Server thread/INFO]: [InfinityDispenser] Disabling InfinityDispenser v1.7
[23:08:32] [Server thread/INFO]: [SmartLifts] Disabling SmartLifts v1.0.1
[23:08:32] [Server thread/INFO]: [0;34;1m[SmartLifts] [0;36;1m=== DISABLE START ===[m
[23:08:32] [Server thread/INFO]: [0;34;1m[SmartLifts] [0;36;1m=== DISABLE COMPLETE (0ms) ===[m
[23:08:32] [Server thread/INFO]: Saving players
[23:08:32] [Server thread/INFO]: wd40bomber7 lost connection: Server closed
[23:08:32] [Server thread/INFO]: wd40bomber7 left the game.
[23:08:32] [Server thread/INFO]: Saving worlds
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Empathy'/Overworld
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Empathy_nether'/Nether
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Empathy_the_end'/The End
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Atlas'/Overworld
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Sanctuary_The_End'/The End
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Sanctuary_Nether'/Nether
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Survival_Nether'/Nether
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Hyperion_The_End'/The End
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Survival'/Overworld
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Minigames'/Overworld
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Survival_The_End'/The End
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Hyperion'/Overworld
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Plotworld'/Overworld
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Hyperion_Nether'/Nether
[23:08:32] [Server thread/INFO]: Saving chunks for level 'Sanctuary'/Overworld
`

I would also note if all players have logged out, the cache should be empty, and this function will do no harm. At the very least you should detect that your assumption (the cache is empty) is true on shutdown, and you should warn if it isn't.

**Comment by Gnat008** [comment]
Weird.... Ours don't do that. Could you open a new PR with the flush fix? I just made some extensive changes, but I don't think they'll affect this code. The items things are fixed now so no need to worry about that. Also please use spaces and not tabs. :)

**Pull request closed without merging**
