### PR TITLE
Fix the java.io.FileNotFoundException

### PR DESCRIPTION
**Pull request by xiurobert**
I use this plugin and there was this error

### CODE REVIEW

**Comment by Gnat008** [comment]
Mm no, '__default.json' is the correct file name there. Whats the stacktrace you're seeing?

**Comment by xiurobert** [comment]
12:52:32 WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (The system cannot find the file specified)
[12:52:32 WARN]:        at java.io.FileInputStream.open0(Native Method)
[12:52:32 WARN]:        at java.io.FileInputStream.open(Unknown Source)
[12:52:32 WARN]:        at java.io.FileInputStream.<init>(Unknown Source)
[12:52:32 WARN]:        at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[12:52:32 WARN]:        at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[12:52:32 WARN]:        at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[12:52:32 WARN]:        at me.gnat008.perworldinventory.commands.ReloadCommand.executeCommand(ReloadCommand.java:28)
[12:52:32 WARN]:        at me.gnat008.perworldinventory.PerWorldInventory.onCommand(PerWorldInventory.java:295)
[12:52:32 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:52:32 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:52:32 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[12:52:32 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:633)
[12:52:32 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
[12:52:32 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
[12:52:32 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[12:52:32 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[12:52:32 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:52:32 INFO]: ╗ Configuration files reloaded!

**Comment by Gnat008** [comment]
I believe this is fixed in the current (unreleased) code, if I remember correctly. Try building the current master branch, and trying that.

**Comment by xiurobert** [comment]
Ok

**Comment by xiurobert** [comment]
nope, worlds still not working. Inventory remains the same despite the world?

**Comment by ljacqu** [comment]
To chime in, 

> plugins\PerWorldInventory\data\**defaults__default.json**

seems to me there's a folder separator missing somewhere? Though based on the stacktrace (`GroupManager.java:187`) I don't see where that would be happening.

**Comment by xiurobert** [comment]
The file located in data/defaults/ is named default.json, not __default.json

**Comment by ljacqu** [comment]
I think the idea is that it's called default.json in the JAR but copied as __default.json to the plugin folder. Note that the exception has default**s** in it, with an S.

However, I think there might be an issue here at https://github.com/Gnat008/PerWorldInventory/blob/master/src/main/java/me/gnat008/perworldinventory/PerWorldInventory.java#L93 because somehow there's an existence check for a __default.json and then I only see manipulations on files called default.json.

**Comment by Gnat008** [comment]
...Yeah, that would be why. Looks like I don't rename the file when moving 
it. I wonder if there was a reason I didn't just name the file 
__default.json in the jar file. Seems like that would be a good idea.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by xiurobert** [comment]
So a file rename would be better?

**Comment by Gnat008** [comment]
I'm thinking so, by renaming the file in the resources folder to '__default.json' (IntelliJ IDEA will also automatically change the reference to it in PerWorldInventory.java). And making sure it doesn't break anything else in the process.

I can't do that right this second myself as I've got other uncommitted changes that I don't want to commit yet prematurely, so if you or someone wants to do it, make a new PR for it.

**Comment by ScuroK** [comment]
@Gnat008 could you please take 2 minutes and tell the people on the spigot forum what is going on???
 We all worry about PWI being abandoned!
(See resource discussion)

**Comment by xiurobert** [comment]
Ok I'll change the PR at home

**Comment by Gnat008** [comment]
To make things easier, I just did this myself. 225ae40

**Pull request closed without merging**
