### PR TITLE
Initialization test

### PR DESCRIPTION
**Pull request by ljacqu**
I was curious that 

```java
public class ItemSerializer {

    @Inject
    private static PerWorldInventory plugin;
```

didn't throw an error (`@Inject` on a static field not supported by default) and decided to check in form of an initialization test. I didn't fix the field; please note that it will always be `null` as it is currently because it doesn't go through the injector (therefore no error, either).

### CODE REVIEW

**Comment by Gnat008** [comment]
Hm I didn't realize that. Making it non-static would be pretty tricky I think, and having a plugin reference is needed because it needs to make ItemMeta's.... This may require some thought.

**Comment by ljacqu** [comment]
I can't think of a way to keep the classes static and fixing it with the injector (and a custom handler), because the injector, in its foundation, deals with instances of a class... However, I changed the classes to instance classes on a branch and it worked great.

Only issue is that the FileWriterTest doesn't work anymore. This is a missing feature of the injector's test runner, supporting multiple `@InjectDelayed` fields or maybe a new way to construct anything needed automatically that isn't provided as `@Mock` field.

**Comment by ljacqu** [comment]
since I tried it out I might as well create a PR -> #81, if you don't like it just close it please ;) Contains the same changes as in this PR. Both PR's aren't failing btw, the build servers are having trouble getting Vault.

```
[ERROR] Failed to execute goal on project perworldinventory: Could not resolve 
dependencies for project me.gnat008:perworldinventory:jar:1.8.0: Could not transfer 
artifact net.milkbowl.vault:VaultAPI:jar:1.5 from/to vault-repo 
(http://nexus.theyeticave.net/content/repositories/pub_releases): 
nexus.theyeticave.net: Unknown host nexus.theyeticave.net -> [Help 1]
```

**Comment by Gnat008** [comment]
Ah, interesting. I'll close this one and merge the other once, since that one has the changes from this one.

**Pull request closed without merging**
