### PR TITLE
Real stuff from the previous PR by @ExileDev

### PR DESCRIPTION
**Pull request by sgdc3**
Thanks to @ExileDev

### CODE REVIEW

**Comment by sgdc3** [comment]
The 70% of the enhancements are pom/dependency related. ;)

**Comment by Gnat008** [comment]
This looks good, except for one thing:
In EconomySerialization.java, you are using the deprecated method for getBalance(). I am already using the correct method.

**Comment by sgdc3** [comment]
Do you mean the Player.name to String convertion?

My IDE says:
```
The method depositPlayer(String, double) in the type Economy is not applicable for the arguments 
The method getBalance(String) in the type Economy is not applicable for the arguments (Player)	The method getBalance(String) in the type Economy is not applicable for the arguments (Player)
```

**Comment by sgdc3** [comment]
ok I found why my ide says that

**Comment by sgdc3** [comment]
reverted ;)

**Comment by sgdc3** [comment]
@Gnat008 Now it's ok?

**Comment by sgdc3** [comment]
@Gnat008 If you want you can also add a Travis Ci badge with the build status and link the project to Circle CI ;)

**Comment by sgdc3** [comment]
@Gnat008 You should also register the plugin on McStats.org!

**Comment by Gnat008** [comment]
@sgdc3 Yeah, will do. Also, how did you fix the Economy thing? After merging it on my system it did the same thing as you said. I temp fixed it by adding Vault as a project dependency.

**Comment by sgdc3** [comment]
http://milkbowl.github.io/VaultAPI/net/milkbowl/vault/economy/Economy.html#getBalance(org.bukkit.OfflinePlayer,%20java.lang.String) I think we should use the OfflinePlayer type :/

**Comment by Gnat008** [comment]
Yes, that's what i'm doing. Maven seemed to like getting some way out of data version of Vault from idk where, causing it to think that method didn't exist.

**Comment by sgdc3** [comment]
Maven automatically downloads the javadocs! :) This is the reason!

**Comment by Gnat008** [comment]
I fail to see what JavaDocs have to do with it...

**Comment by sgdc3** [comment]
I think the IDE checks for additional data from the javadocs, I can't find another way to explain the issue :/

**Comment by Gnat008** [comment]
That makes no sense. It's downloading something entirely unrelated to Docs, or anything else that I can see.

**Comment by sgdc3** [comment]
Ok, anyway the OfflinePlayer type is correct ;)

**Comment by Gnat008** [comment]
Ah, found it. For some reason, when using MultiVerse 2.5 as a dependency, it downloads Vault 1.2.27. Changing MV version back to 2.4 fixes the problem.

**Comment by sgdc3** [comment]
We can use Multiverse 2.5, just add Vault in the exclusion list of the Multiverse dependency ;)

**Comment by Gnat008** [comment]
Done!
/blames MultiVerse. lol

**Comment by sgdc3** [comment]
;)

**Pull request merged**
