### PR TITLE
NexusInventory patches 

### PR DESCRIPTION
**Pull request by ExileDev**
These are most of the patches I put into NexusInventory, and I hope to drop NexusInventory and just help with PWI.

I'm also going to work on the logo as it's not my best work.

### CODE REVIEW

**Comment by ExileDev** [comment]
Ok fixed the small error on startup everything should be good now.

**Comment by Gnat008** [comment]
Okay, let's get started.

* I am all for removing the .idea stuff, that's good.
* README.md
  - You have NexusInventory instead of PerWorldInventory.
* pom.xml
  - What's with the <properties> stuff?
  - You changed the API dependency, why?
* DefaultVals.java: ...Why?
* Logger package
  * ConsoleHandler
    - Line 30 can be shortened to plugin.getLogger()
    - Why have this anyway, when plugin.getLogger() has all of these methods already?
  * Handler.java, PWILogger.java: Why?
* Metrics.java
  - Are most things 'final' for a reason?
  - The config stuff there should prolly be tied into the existing config package, for consistency and to remove potential conflicts.
  - Other than that, that would be okay
* Package names: According to Java conventions, package names should be all lowercase.
* Serialization:
  * Author of TacoSerialization requests that his package names be kept as they were originally.
  * The only reason they are still around is for reading legacy data
  * SingleItemSerialization.java
    - Forgetting the above point, why are we checking the version? Hell, this doesn't even run on 1.7.
* SpigotUpdater.java
  - Not sure how I feel about an updater yet
  - Variable names: What do they mean/what are they for? var# isn't very descriptive.
* ChatColor.java: Why?
* MinecraftUtils.java: Why? PWI doesn't even run on 1.7.
* PlayerMessager.java
  - Can prolly be placed as a method in the main class. :/
  - Doesn't have the 'warn' functionality of the Printer class method
* plugin.yml: Do those variables work? O.o
* ConfigValues.java: You add a config option, but fail to update the key checking in the getKey() method, potentially breaking things.

**Comment by sgdc3** [comment]
60% of the project structure changes (pom,external json,minecraft utils and etc...) are mine commits brutally copied from the old PerWorldItems repo. -_- I will post a PR on ExileDev's repo to fix all the pom related issues...

**Comment by sgdc3** [comment]
I will replace metrics with the official maven version ;)

**Comment by sgdc3** [comment]
And please, no auto-updater....

**Comment by sgdc3** [comment]
Nah, it's better to chose the good enchancements and add them one by one ;)

**Comment by Gnat008** [comment]
Agreed with @sgdc3. Gonna close this. Take into account our input, and make pull requests for individual issues, not one huge blanket PR. :)

**Comment by sgdc3** [comment]
@ExileDev I'm working on a pull request with only the real enhancements ;)

**Comment by sgdc3** [comment]
Done, look at PR #25 @Gnat008

**Pull request closed without merging**
